### ISSUE TITLE
Django auf virtuellem Server aufsetzen

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/DjangoImageShop#10]
User Story: #1 
Task-ID: 1.2

Bearbeitet von: Tom

**Comment by Tomatenbiss** [comment]
Task erledigt.

Wurde beim Daily Scrum noch nicht besprochen.

**Comment by OHDMax** [comment]
Wie besprochen, würde ich mich drum kümmern.

**Comment by Tomatenbiss** [comment]
Achse, hab ich als fertig angesehen da mit dem Readme ja quasi die Anleitung kam. Aber stimmt, muss auf der VM ja noch einmal umgesetzt werden. @warlockerino kannst du die Server-Mail an uns weiterleiten?

**Comment by OHDMax** [comment]
@Tomatenbiss  hast du das mit #27 erledigt?
