### ISSUE TITLE
Validierungslogik (Registrierung) einbinden

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/DjangoImageShop#11]
Userstory: #3
Task-ID: 3.1

Bearbeitet von:

**Comment by OHDMax** [comment]
Das nimmt uns doch Django ab oder? Können wir das dann nicht zumachen?

**Comment by OHDMax** [comment]
Erledigt von Django.

**Comment by OHDMax** [comment]
@captainkingcandy Bezüglich des html, das escaped wird, vielleicht hilft dir ja der Link hier:
https://docs.djangoproject.com/en/1.11/ref/templates/language/#for-template-blocks

**Comment by captainkingcandy** [comment]
@OHDMax Danke, sollte jetzt gefixt sein
