### ISSUE TITLE
User Datenmodell entwickeln

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/DjangoImageShop#13]
User Story: #3 
Task-ID: 3.3

Bearbeitet von:

**Comment by OHDMax** [comment]
@Tomatenbiss @captainkingcandy @warlockerino @MuhammedErek War hier auch das Erstellen der Profilseite enthalten?

**Comment by Tomatenbiss** [comment]
Dieser Task ist Teil der User Story "Benutzerlogik aufsetzen". Ist nun Interpretationssache, ob zu der Story auch das Erstellen der Profilseite gehört. In die Task gehört sie aber nicht würde ich sagen. Ich leg gleich noch den Task an.

**Comment by OHDMax** [comment]
Django stellt ja schon ein UserModel zur Verfügung. Ich bin dafür wir nehmen erstmal das und erweitern es dann später, wenn wir z.B. den Warenkorb erstellen.

**Comment by OHDMax** [comment]
Für den Fotografen und Nutzer erweitern wir das Datenmodell

**Comment by OHDMax** [comment]
Model ist soweit in Ordnung. Wird dann in anderen Tasks erweitert.
