### ISSUE TITLE
View für den Shop anlegen

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/DjangoImageShop#16]
Userstory: #12 
Task-ID: 12.1

Bearbeitet von:

**Comment by OHDMax** [comment]
Das sind ja eigentlich zwei Views: 
  *  einen wo man alle Fotografen sieht und einen Shop auswählen kann
  *  eine Ansicht, wo man alle Fotos des Fotografen sieht, die öffentlich sichtbar sind

**Comment by OHDMax** [comment]
Hab die Übersicht mit allen Shops in #52 ausgelagert

**Comment by OHDMax** [comment]
Wenn du das gemacht hast, könntest du die viewAll Photo View entfernen?
