### ISSUE TITLE
Nutzerprofil bearbeitbar machen

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/DjangoImageShop#18]
Entstanden aus dem Task "User Datenmodell entwickeln". Wurde noch nicht im Daily Scrum diskutiert. 

Hätte dann folgende Metadaten:
User Story: #3
Task-ID: 3.4

**Comment by OHDMax** [comment]
Unter welcher Adresse soll denn die UserView angezeigt werden?

**Comment by Tomatenbiss** [comment]
Fehlt noch die Anbindung an das Model. Ist in Bearbeitung.

**Comment by OHDMax** [comment]
*  Edit Sicht für das eigene Nutzerprofil anlegen.

**Comment by MuhammedErek** [comment]
Sollte ich nicht lieber dieses Issue machen, da Tom schon viel anderes diesen Sprint zu tun hat?
Außer ihr habt euch dabei etwas gedacht.

**Comment by OHDMax** [comment]
Tom wollte das machen, hat er beim Sprint Planning gesagt.

**Comment by OHDMax** [comment]
Sieht gut aus @captainkingcandy, bist du soweit durch damit?

**Comment by captainkingcandy** [comment]
ja, ich würde sagen das ist durch

**Comment by Tomatenbiss** [comment]
Ich danke euch :) Server ist jetzt fertig!
