### ISSUE TITLE
Model für Fotograf entwickeln

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/DjangoImageShop#20]
Userstory: #2
Task-id: 2.1

**Comment by Tomatenbiss** [comment]
Neue App anlegen

**Comment by captainkingcandy** [comment]
Benötigen wir für den Fotografen wirklich ein Modell? Wenn ja, was Felder soll das Modell enthalten? Stehe da gerade ein bisschen auf dem Schlauch... Kunden und Fotografen sind ja beides User, und werden dann nach der Registrierung der jeweiligen Benutzergruppe (Fotograf oder Kunde) zugeordnet. Bilder und Bilderserien werden dem Fotografen dann ja direkt über den Benutzernamen zugeordnet, oder sehe ich das falsch?

**Comment by OHDMax** [comment]
Ich glaube es wäre sinnvoll, wenn man die Fotos und den Warenkorb an den User hängt. Dann können wir einfacher auf dies Entitäten zugreifen. Ansonsten müssen wir immer über alle Fotos/Warenkörbe iterieren um den Warenkorb/Foto für den jeweiligen User zu bekommen.

**Comment by OHDMax** [comment]
@warlockerino guck mal, was bei dir schon gemacht ist.
