### ISSUE TITLE
Hochladen der Fotos implementieren

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/DjangoImageShop#24]

**Comment by OHDMax** [comment]
Implementiert. Bin mir allerdings ziemlich sicher, dass die momentane Lösung mit dem Deployment nicht funktioniert.

**Comment by OHDMax** [comment]
In der Bearbeiten und Hochladen View soll noch gesetzt werden können, ob das Bild sofort sichtbar ist. Das muss ich noch nachziehen.

**Comment by OHDMax** [comment]
Bild kann jetzt als öffentlich markiert werden.

**Comment by captainkingcandy** [comment]
Der Upload von Bilder funktioniert bei mir nicht mehr, seit dem in der Datei photo/models.py Folgendes geändert wurde:

`owner = models.ForeignKey('accounts.Photographer')`

so funktioniert es dann wieder

`owner = models.ForeignKey(User)`

**Comment by OHDMax** [comment]
Die Änderung kam durch den Commit 1852977c64bb192722fd71817082c25f88b3d30e von @warlockerino. Hab das spontan nicht gefixt bekommen, hab das deshalb an ihn weitergegeben.

**Comment by OHDMax** [comment]
Es fehlt die "Löschen" Operation

**Comment by OHDMax** [comment]
Löschen ist möglich.
