### ISSUE TITLE
Designs vorschlagen

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/DjangoImageShop#25]
Bootstrap 4
Insgesamt 5 Vorschläge

**Comment by MuhammedErek** [comment]
Hier mal eine Alternative für Bootstrap: Material Design mit Bootstrap Geschmack.

Landingpage:
https://mdbootstrap.com/freebies/ecommerce-homepage-template/?utm_id=424d4d

Product shop:
https://mdbootstrap.com/freebies/ecommerce-product-page-template/?utm_id=424d4d

**Comment by OHDMax** [comment]
GroundworkCSS
https://groundworkcss.github.io/groundwork/?url=docs/layout-c

PureCSS
https://purecss.io/layouts/gallery/

**Comment by Tomatenbiss** [comment]
https://github.com/rdash/rdash-angular

http://demos.creative-tim.com/material-dashboard/examples/dashboard.html?_ga=2.87475224.1260668322.1511339814-1460480451.1511339814

http://sb-admin-bs4.strapui.com/index.html

https://medialoot.com/preview/frame/bootstrap-4-dashboard.html

**Comment by Tomatenbiss** [comment]
Es wurde gewählt:

GroundworkCSS
https://groundworkcss.github.io/groundwork/?url=docs/layout-c
