### ISSUE TITLE
View für die Anzeige aller Bilder

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/DjangoImageShop#26]
Es werden nur freigegebene Bilder angezeigt

**Comment by MuhammedErek** [comment]
Da wir das mit dem Freigeben noch nicht wirklich implementiert haben (außer im Model), habe ich es bei der Anzeige aller Bilder erstmal ausgelassen, damit man morgen etwas zum Vorzeigen hat.
Die View ist über photo/view aufrufbar (ohne pk).

**Comment by OHDMax** [comment]
Ich implementiere das noch in #24 und dann kannst du das mit dem `public` mitmachen

**Comment by OHDMax** [comment]
Ich hab das mal eben mitgemacht. Der ListView zeigt jetzt nur noch öffentlich sichtbare Bilder an.
