### ISSUE TITLE
Dokumentation von Nutzern

### ISSUE THREAD

**Issue by OHDMax** [Tomatenbiss/DjangoImageShop#28]
Wir haben viele Nutzer in der Datenbank, aber nirgendwo sind sie dokumentiert (z.B. kenne ich von keinem das Passwort). Wollen wir uns mal Testnutzer anlegen (für jede Rolle einen) und Nutzernamen und Passwort dokumentieren?

**Comment by captainkingcandy** [comment]
Die bisherigen Benutzer haben alle das Passwort: test12345

**Comment by OHDMax** [comment]
So, ich hab jetzt alle User rausgeschmissen außer:
Customer:
  *  dirkbach 
  *  udowalkes

Photographer
  *  klausmeier
  *  klausdieter

und den admin "admin2". Ich lege nachher noch eine Seite im Wiki an.

**Comment by OHDMax** [comment]
Seite ist fertig. Findet man im SDF Wiki unter https://wiki-sdf.f4.htw-berlin.de/wiki/DokF3_2017
