### ISSUE TITLE
Dokumentation der App Struktur

### ISSUE THREAD

**Issue by OHDMax** [Tomatenbiss/DjangoImageShop#29]
Ich wäre dafür, wir dokumentieren unsere App Struktur. Was haltet ihr davon?

**Comment by captainkingcandy** [comment]
Ja, finde ich ne sinnvolle Sache...

**Comment by OHDMax** [comment]
Kannst das auf der Seite eintragen, die ich schon in #28 angelegt habe.

**Comment by OHDMax** [comment]
Kannst das auf der Seite eintragen, die ich schon in #28 angelegt habe.

**Comment by MuhammedErek** [comment]
Es wurde eine Doku für die Ordnerstruktur hier eingefügt: https://wiki-sdf.f4.htw-berlin.de/wiki/DokF3_2017
