### ISSUE TITLE
Dokumentation der Entities/des Datenmodells

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/DjangoImageShop#32]

**Comment by Tomatenbiss** [comment]
Hey Leute, hier mal eine Übersicht des aktuellen Datenmodells sowie zwei Vorschläge wie es umgesetzt werden könnte. Feedback wäre nett, dann würde ich die Tabellenstruktur ausarbeiten..

Liebe Grüße
Tom
[ProposalDBModel.pdf](https://github.com/Tomatenbiss/DjangoImageShop/files/1545097/ProposalDBModel.pdf)

**Comment by OHDMax** [comment]
Den ersten Vorschlag mit der "Order" Entity finde ich gut. Mir gefällt das aber nicht so, dass die Order zu mehreren Photographen zugeordnet wird. Ich fände es besser (einfacher?) im Warenkorb nur Fotos aus einem Shop zu akzeptieren und die "Order" nur einem Fotografen und einem Kunden zugeordnet wird. Was meint ihr?

**Comment by Tomatenbiss** [comment]
Das wäre dann quasi das, was ich mit Option 2 ausdrücken wollte. Das aktuelle Datenmodell hat halt noch keine Shops. Ich arbeite den Vorschlag genauer aus und poste ihn hier nochmal.

**Comment by Tomatenbiss** [comment]
Hier das kleine Update: Jeder Photograph hat einen Customer. Beim Einkaufen sollte dann nur noch gecheckt werden, ob er gerade versucht, seine eigenen Bilder zu kaufen.
[ProposalDBModel_v03.pdf](https://github.com/Tomatenbiss/DjangoImageShop/files/1571590/ProposalDBModel_v03.pdf)
