### ISSUE TITLE
View/Edit für Warenkorb

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/DjangoImageShop#33]

**Comment by MuhammedErek** [comment]
Lukas hat hier schon eine basic view für die Warenkorbansicht gemacht. Ich kam leider diese Woche garnicht dazu hier wirklich was zu machen.
Ich würde vorschlagen, dieses Issue im nächsten Sprint erneut mit reinzunehmen, inklusive aller Warenkorboperationen (falls wir diese Userstory diesen Sprint kriegen). Dann würde ich die View auch vollständig bearbeiten.

**Comment by OHDMax** [comment]
Es fehlt die "Löschen" Operation

**Comment by captainkingcandy** [comment]
Das Löschen einzelner Fotos wurde nun in den View integriert. Dann habe ich noch eingefügt, dass man jedes Bild nur einmal in den Warenkorb hinzufügen kann. Haben wir ja bereits besprochen, dass es bei digitalen Bildern eigentlich keinen Sinn macht, diese mehrfach zu kaufen. Fotografen sehen den Warenkorb jetzt auch und können Bilder zum Warenkorb hinzufügen oder aus dem Warenkorb löschen.

**Comment by OHDMax** [comment]
*  Die Tabelle soll schöner werden 
*  Buttons ausblenden und Text anzeigen, wenn Warenkorb leer
*  Quantity raus
