### ISSUE TITLE
Warenkorblogik

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/DjangoImageShop#37]
Bearbeiten, Hinzufügen, Löschen

**Comment by captainkingcandy** [comment]
Eine Vorabversion ist implementiert und kann auf folgende Weise benutzt werden:

`/shoppingcart/add/?id=1
/shoppingcart/show/
/shoppingcart/remove/?id=1`

Die id steht für die Id des jeweiligen Fotos, Fotoserien können noch nicht hinzugefügt werden.
