### ISSUE TITLE
Sämtliche Templates auf MdBootstrap umstellen

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/DjangoImageShop#38]
https://groundworkcss.github.io/groundwork/?url=docs/layout-c

**Comment by MuhammedErek** [comment]
Framework sehr veraltet, siehe https://github.com/groundworkcss/groundwork 

Es gab viele Schwierigkeiten das Projekt auf Groundwork umzustellen, weshalb nun nach Absprache mit dem Team, der PO informiert wurde.
Nach seiner erneuten Entscheidung werde ich dieses Issue umbenennen und dann weiter bearbeiten.

**Comment by MuhammedErek** [comment]
Die Antwort kam schnell. Das neue Framework wird seine zweite Wahl: https://mdbootstrap.com/ sein.
