### ISSUE TITLE
Model für Kategorie

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/DjangoImageShop#39]

**Comment by OHDMax** [comment]
Hab die Kategorie ganz 'dämlich' implementiert. Sie hat nur einen Namen, aber weiß ansonsten von nix.

**Comment by OHDMax** [comment]
Hab mich auch gefragt, ob Kategorien per Nutzer einzigartig sein sollen, aber hab mich dagegen entschieden, weil das zuviel Komplexität reinbringt.

**Comment by captainkingcandy** [comment]
Irgendwie kriege ich da gerade folgenden Fehler: 
ValueError: Dependency on unknown app: photograph

In der /photoseries/migrations/0001_initial.py steht folgendes:

```
        migrations.CreateModel(
            name='Photoseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('describtion', models.CharField(max_length=100)),
                ('images', models.ManyToManyField(to='photograph.Photo')),
```

Haben wir überhaupt ne app die photograph heißt? Kann das sein, dass du evtl einfach photo meinst?

**Comment by OHDMax** [comment]
Das ist nicht von mir, das ist von @warlockerino

**Comment by captainkingcandy** [comment]
Kann gelöst werden in dem der migrations Ordner unter photoseries gelöscht wird!
