### ISSUE TITLE
Provisorischer View + Logik für Kategorie erstellen

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/DjangoImageShop#40]

**Comment by OHDMax** [comment]
Kategorien können über die URL `photo/categories/` angelegt werden. Außerdem ist es möglich, die Kategorien per AJAX anzulegen. Das werden wir später noch benötigen, wenn wir Kategorien zu Fotos hinzufügen wollen, die vorher noch nicht existierten.
