### ISSUE TITLE
Navigationskonzept erstellen

### ISSUE THREAD

**Issue by OHDMax** [Tomatenbiss/DjangoImageShop#48]

**Comment by OHDMax** [comment]
Navigationskonzept ist erstellt und z.T. auch implementiert. Ich dokumentiere es in meinem nächsten Blogeintrag.

**Comment by OHDMax** [comment]
Blog schaffe ich bis morgen nicht, daher einen Überblick im Issue hier. Müsst ihr jetzt nicht lesen, aber wenn ihr neue Views implementiert, schaut hier nach, wo sie hin soll.

## Shops
Auf der Landingpage alle Shops angezeigt werden. Wenn man dann auf einen Shop klickt, öffnet sich die Liste mit allen sichtbaren Fotos und Fotoserien des Shops. Wenn man ein Bild anklickt, kommt man auf die Detailseite, wo man das Bild kaufen kann. 
>> Ist man als Fotograf angemeldet und das Bild gehört einem, kann man hier das Bild auch bearbeiten und Löschen. Nach dem Löschen sollte man zum Shop zurück.

## Bestellungen
Bestellungen werden über den Warenkorb ausgelöst. Er ist über das entsprechende Icon in der Navbar erreichbar. Im Warenkorb gibt es zwei Möglichkeiten: Leeren und Bestellung auslösen. "Bestellung auslösen" führt zu einer Bestätigungsseite, die die Zahlungsmethode anzeigt und zwei Buttons enthält: `Kaufen` und `Abbrechen`.
>> Kaufen > Bestätigungsseite, Vielen Dank und Link zur Startseite zurück.
>> Abbrechen > Zurück zum Warenkorb

## Nutzerfunktionen
### Fotograf - Hochladen von Fotos/Fotoserien
Für den Fotografen gibt es in der Navbar ein neues Dropdown: `Upload`.
Dort gibt es zwei Links: Foto hochladen und Fotoserie hochladen. Die Funktion dürfte selbsterklärend sein ;) Auf der Upload-Seite gibt es zwei Links: `Hochladen` und `Abbrechen`.
>> Hochladen führt zur Detailseite des Bilders
>> Abbrechen führt zur vorherigen Seite

### Fotograf - Verwalten von Fotos/Fotoserien
Der Name des eingeloggten Nutzers in der Navbar ist jetzt auch ein Dropdown. Zum Verwalten von Fotos gibt es zwei neue Seiten: `Meine Fotos` und `Meine Fotoserien`. Beide Seiten führen jeweils zu einer Übersicht von den Entitäten, die dem Nutzer gehören, egal ob öffentlich oder nicht.
(Notiz: Ich fände es besser, diese Sachen nicht auf die Profilseite zu bringen, weil es in Django fast nix kostet ListViews für einzelne Entitäten anzulegen). Ein Klick auf ein Element in dieser Liste führt zur Detailseite des Elements, wo man wieder bearbeiten und löschen kann.
>> Bearbeiten führt zur Detailseite zurück
>> Löschen sollte zur Übersicht zurückführen

### Fotograf - Offenen Bestellungen
Ebenfalls im Dropdown mit dem Nutzernamen gibt es den Punkt `Offene Bestellungen`. Auf dieser Seite sieht der Fotograf alle Bestellungen, die er noch nicht bestätigt hat und kann diese Bestätigen. Auf dieser Seite gibt es keine Buttons.

### Nutzer und Fotograf - Profilseite
Ebenfalls im Dropdown mit dem Nutzernamen gibt es einen Link zum (eigenen) Profil. Ob wir sowas brauchen, ist bis jetzt nicht geklärt. Auf dieser Seite gibt es (noch) keine Buttons.

Noch offen: Es fehlt ein Link auf der Detailseite eines Bildes, der entweder zurück zum Shop oder zur Übersicht zu kommen.

**Comment by OHDMax** [comment]
*  Landingpage -> alle Fotos von allen Fotografen
*  "Photos" zu "Shops" ändern und dort alle Shops anzeigen. 
*  Highlighting ändern und den aktuellen Tab auf Active setzen (Beim User Profil der User Name, Bei Shops die Shops.)
*  Bei meine Fotos den Namen der Seite ändern

**Comment by MuhammedErek** [comment]
Ist nun abgeschlossen. Falls euch etwas optisch nicht gefällt (z.B. die rote farbe beim active oder der schwarze hintergrund beim highlighting), könnt ihr einfach bescheid sagen, oder selber anpassen.
