### ISSUE TITLE
Upload Verzeichnis zu media/photos ändern

### ISSUE THREAD

**Issue by OHDMax** [Tomatenbiss/DjangoImageShop#50]

**Comment by MuhammedErek** [comment]
Wo wurde das nun verändert?
Habe kein Commit dazu gefunden.
Habe direkt mit meinem Issue angefangen gehabt, als ich gesehen habe, dass es done ist. Das Issue mit dem Apps ins Plural setzen. Nun sieht man keine fotos mehr, weil ich das alte photos Ordner gelöscht habe. Hast du einen Plan, wieso?

**Comment by MuhammedErek** [comment]
Sorry mein Fehler, ich musste leider bei photos usw die migrations löschen und neu generieren. Da wurden dann auch alle Fotos gelöscht anscheinend. Mein Kommentar kann also ignoriert werden
