### ISSUE TITLE
Alle Apps in den Plural setzen

### ISSUE THREAD

**Issue by OHDMax** [Tomatenbiss/DjangoImageShop#51]
Erst nach #50 erledigen

photo -> photos
shoppingcart -> carts
shop -> shops

Bitte danach auch in der Doku ändern.

**Comment by MuhammedErek** [comment]
Wurde umgesetzt. Es war leider nötig die alten migrations zu löschen und sie neu zu erstellen. Hoffe das erzeugt bei niemandem ein Problem.
Ansonsten bei Unklarheiten der Appstruktur in der Doku nachlesen, diese ist nun aktuell.
