### ISSUE TITLE
Zwei Shoppingcart Models im Code

### ISSUE THREAD

**Issue by OHDMax** [Tomatenbiss/DjangoImageShop#53]
Wir haben zwei verschiedene Shoppingcart Models im Code: `carton` und `shoppingcart`. Welcher davon kann gelöscht werden?

**Comment by captainkingcandy** [comment]
Beide werden gebraucht:

`shoppingcart` enthält die urls.py und die logik (views.py) für das Anzeigen, Hinzufügen und Löschen des Warenkorbs.

`carton` ist die App, für die vermutlich am Besten die Beschreibung "Bestellung" passen würde. Hier ist festgelegt wie ein Produkt, dass sich im Warenkorb befindet auszusehen hat und was für Eigenschaften es haben muss.

**Comment by OHDMax** [comment]
Das ist ne externe Abhängigkeit oder? Wäre mir lieber, wenn wir das über pip installieren würden.

Ist iamgefit auch ne externe Abhängigkeit?

**Comment by OHDMax** [comment]
Ich hab beides in die `requirements.txt` ausgelagert.

**Comment by captainkingcandy** [comment]
Da nun `carton` und `imagefit` in die requirements.txt verschoben wurden kommt es bei der Installation der Requirements in einer python3 virtual environment zu folgendem Fehler:

[https://github.com/vinyll/django-imagefit/issues/14](url)

Leider wurde dieser von den imagefit Entwicklern noch nicht behoben... Verwendet man eine python2.7 virtual environment, so bekommt man bei der Installation jedoch keine Probleme.

Wäre dann dementsprechend einfach:

`virtualenv -p python env`

statt bisher:

`virtualenv -p python3 env`
