### ISSUE TITLE
Fotograf kann Bilder kategorisieren

### ISSUE THREAD

**Issue by OHDMax** [Tomatenbiss/DjangoImageShop#56]
Dafür stehen ihm alle Kategorien zur Verfügung, es wird nicht unterschieden, wer eine Kategorie erstellt hat.

**Comment by Tomatenbiss** [comment]
Photos können nun kategorisiert werden. Leider ist das noch etwas unschick, Django standard Ansicht zeigt die Liste und man muss alle markieren, die zugewiesen werden sollen.. Kategorien können nun auch gelöscht werden. Hat jemand von euch eine Idee, wie man das schicker machen kann oder anderweitiges Feedback?

**Comment by OHDMax** [comment]
Die ganze Form ist nicht so schön, daher sehe ich das nicht so kritisch und finde, dass wir das so lassen können.

**Comment by Tomatenbiss** [comment]
Sauber, danke fürs schnelle Feedback, ich mach das Issue dann jetzt zu

**Comment by Tomatenbiss** [comment]
Ups, meine markiere es als done
