### ISSUE TITLE
Nach Bildtitel/Bildserientitel suchen

### ISSUE THREAD

**Issue by OHDMax** [Tomatenbiss/DjangoImageShop#57]
*  Suchzeile in der Navigationsbar anlegen
*  View für die Suchergebnisse anlegen
*  Suchmethode anlegen

**Comment by OHDMax** [comment]
Man kann noch nicht nach Bildserien suchen.

**Comment by MuhammedErek** [comment]
Ist es nicht sinnvoll einfach immer nur das Ergebnis der Suche anzuzeigen. Für das Ergebnis ist es theoretisch irrelevant, ob der suchtext in einer serie oder in der beschreibung/titel eines bildes usw. ist.
Oder war es explizit so gewollt?

**Comment by OHDMax** [comment]
Kann mich nicht erinnern, dass es so gefordert war, kannst du also so machen.

**Comment by MuhammedErek** [comment]
Hab es geändert, bitte einmal austesten ob alles funzt.

**Comment by OHDMax** [comment]
Bilder, die Kopien für Bestellungen sind, werden jetzt wieder in der Suche angezeigt. Ich fixe das noch.

**Comment by OHDMax** [comment]
Alles klar, sieht sehr schick aus!
