### ISSUE TITLE
Bestellung auslösen

### ISSUE THREAD

**Issue by OHDMax** [Tomatenbiss/DjangoImageShop#61]
Für jedes Foto eine Mail an den Fotografen verschicken und Bestellungen unter "Meine offene Bestellungen" anzeigen.

**Comment by warlockerino** [comment]
Fotograf braucht auch noch eine Ansicht für die ausstehenden Bestellungen

**Comment by warlockerino** [comment]
Komplettes Paket: MVC

**Comment by OHDMax** [comment]
Wir brauchen hier zwei Views. Eine für den Fotografen, dass er Bestellung angucken und freigeben kann und eine für den Käufer, dass er die Bestellung angucken und ggf. runterladen kann.

**Comment by OHDMax** [comment]
Ich könnte morgen das Model anfangen. Hast du schon was hierfür gemacht @MuhammedErek?

**Comment by MuhammedErek** [comment]
Ich kam leider überhaupt nicht dazu :(
Es wäre echt sehr hilfreich, wenn du das Model machen würdest. Ich bin bei dem ganzen View kram schneller dran.
Mach auch am besten eine neu app namens order und pack alles da rein.

**Comment by OHDMax** [comment]
Hab meinen Stand auf einem Branch eingecheckt, mache morgen damit weiter. Wenn du Zeit hast @MuhammedErek könntest du die search_result.html verschönern?

**Comment by OHDMax** [comment]
Noch offen:
  *  E-Mail Versand nach erfolgreicher Bestellung
  *  Checkout View verschönern
  *  Bestellhistorie 
  *  #62

**Comment by MuhammedErek** [comment]
Du hast ja doch mehr gemacht, als gedacht. Bist ein Held :)
Ich hatte in diesem Sprint echt gar keine Zeit um etwas zu tun. Etwas heute und morgen werde ich die ganzen views überarbeiten (auch search_result) und wenn das mit E-Mail noch nicht gemacht wurde, schau ich mir das auch noch an.

**Comment by OHDMax** [comment]
Das mit der Mail kannst du machen, dann würde ich mich um die Downloads in #63 kümmern.
Scheint nicht so schwer zu sein, hier der Link zur Doku: https://docs.djangoproject.com/en/1.11/topics/email/. Der SMTP Server etc ist schon eingerichtet.
