### ISSUE TITLE
Foto: Bestellung freigeben

### ISSUE THREAD

**Issue by warlockerino** [Tomatenbiss/DjangoImageShop#62]
[x] List-View für offenen Bestellungen erstellen.
[x] Detail-View für Bestellung anpassen.
[X] Logik für Button auf dem Detail-View, der dafür sorgt, dass die Bestellung freigegeben wird
[X] Mail an den Kunden versenden, sobald die Bestellung freigegeben wurde
[X] #63

**Comment by OHDMax** [comment]
Hier gehts doch drum, dass der Kunde eine Mail mit dem Link zum Foto bekommt, nachdem der Fotograf bestätigt hat, dass die Bestellung bezahlt wurde oder?

**Comment by OHDMax** [comment]
Noch offen: Mail an den Kunden versenden, sobald die Bestellung freigegeben wurde
