### ISSUE TITLE
Wasserzeichen in Thumbnails

### ISSUE THREAD

**Issue by warlockerino** [Tomatenbiss/DjangoImageShop#64]
Wasserzeichen aus Detailansicht auf Thumbnails übertragen

**Comment by OHDMax** [comment]
Das war noch offen oder @captainkingcandy?

**Comment by captainkingcandy** [comment]
Nee, ist eigentlich auch fertig

Maximilian Schulze <notifications@github.com> schrieb am Mi., 10. Jan. 2018
um 16:25:

**Comment by OHDMax** [comment]
Okay, habe die nämlich nicht gesehen. Müsste man nochmal testen. Reverte ich den commit oder du?
