### ISSUE TITLE
Startseite aufsetzen und anzeigen

### ISSUE THREAD

**Issue by Tomatenbiss** [Tomatenbiss/DjangoImageShop#9]
User Story: #1 
Task-ID: 1.1

Wird bearbeitet von: Tom

**Comment by Tomatenbiss** [comment]
Startseite ist nun erreichbar. Wurde als root view implementiert und kann daher mit localhost:8000 direkt aufgerufen werden. Allerdings sind noch keine Felder zum Einloggen oder Link zur Registrierung vorhanden.

**Comment by OHDMax** [comment]
Links zur Registrierung und zum Login wurden von @MuhammedErek gesetzt. Gibts hier noch Bedarf @Tomatenbiss ?

**Comment by Tomatenbiss** [comment]
Wow, sieht gut aus. Muss die Auswahl "Active/Normal/Disabled" mit rein?

**Comment by OHDMax** [comment]
Ne, das hab ich da nur rein gemacht, um die verschiedenen Zustände der Navs zu zeigen.

**Comment by Tomatenbiss** [comment]
Okay, dann würde ich das als gemacht ansehen. Aus Übersichtsgründen setze ich erstmal ein done-Flag. Können wir ja nachher besprechen ob wir das so beibehalten wollen oder wie die Issues lieber als closed markieren (was heißt, dass sie in dieser Liste nicht mehr einsehbar sind..).
